TYPO3-CMS/styleguide

Classes/Controller/StyleguideController.php
Resources/Private/Language/locallang.xlf
Resources/Private/Templates/Styleguide/Callout.html
Resources/Private/Templates/Styleguide/FlashMessages.html
Resources/Private/Templates/Styleguide/Index.html
ext_tables.php

feel free to update the examples or add additional information.

[TASK] Update FlashMessage and added Callout examples

---

Configuration/TCA/tx_styleguide_forms.php
Configuration/TCA/tx_styleguide_forms_inline_2_child1.php
ext_tables.sql

Added an addMediaUrl example on main records an on IRRE

[TASK] Add addMediaUrl example

---

Configuration/TCA/tx_styleguide_mnsymmetric_hotel.php
Configuration/TCA/tx_styleguide_mnsymmetric_hotel_rel.php
ext_tables.php
ext_tables.sql

This tables and tca are examples taken from irre_tutorial to show inline symmetric relation handling.

Add example for symmetric mm relation

---

Configuration/TCA/tx_styleguide_forms.php
ext_tables.sql

Add an example for the select wizard in combination with a textarea

[TASK] Add example for select wizard

---

Configuration/TCA/tx_styleguide_elements_forms.php
ext_tables.php
ext_tables.sql

[TASK] TCA: forms formwizzard via formEngine

---

Configuration/TCA/tx_styleguide_elements_basic.php
ext_tables.sql

See https://forge.typo3.org/issues/73871

[TASK] TCA: input dbType=date eval=date

---

Configuration/TCA/tx_styleguide_elements_t3editor.php
ext_tables.sql

@lolli42 We allow submitForm of TBE to issued issued via flexForm and bypass
SplitButtons preSubmitCallbacks.

[TASK] TCA: t3editor TBE_EDITOR save via flexForm reload onChange

---

Configuration/TCA/tx_styleguide_inline_mm.php
Configuration/TCA/tx_styleguide_inline_mm_child.php
Configuration/TCA/tx_styleguide_inline_mm_childchild.php
ext_tables.sql

Integrate use-case to store using plain MM intermedia tables with IRRE.

[TASK] Integrate IRRE MM storage

---

Configuration/TCA/tx_styleguide_elements_group.php
ext_tables.sql

see [https://forge.typo3.org/issues/76232](TYPO3 Issue #76232)

TCA: group_db_7 example for showthumbs=true and prepend_tname=false

---

Configuration/TCA/tx_styleguide_elements_group.php
ext_tables.sql

This combination has currently a bug in the core, which will be fixed soon.

[TASK] Add a new example with multiple true and suggest

---

Configuration/TCA/tx_styleguide_elements_rsainput_flex_1_inline_1_child.php
Configuration/TCA/tx_styleguide_elements_rsainput_inline_1_child.php
Configuration/TCA/tx_styleguide_elements_rte_flex_1_inline_1_child.php
Configuration/TCA/tx_styleguide_elements_rte_inline_1_child.php
Configuration/TCA/tx_styleguide_elements_select_single_12_foreign.php
Configuration/TCA/tx_styleguide_elements_t3editor_flex_1_inline_1_child.php
Configuration/TCA/tx_styleguide_elements_t3editor_inline_1_child.php
Configuration/TCA/tx_styleguide_flex_flex_3_inline_1_child.php
Configuration/TCA/tx_styleguide_inline_1n1n_child.php
Configuration/TCA/tx_styleguide_inline_1n1n_childchild.php
Configuration/TCA/tx_styleguide_inline_1n_child.php
Configuration/TCA/tx_styleguide_inline_expand_inline_1_child.php
Configuration/TCA/tx_styleguide_inline_fal.php
Configuration/TCA/tx_styleguide_inline_mm.php
Configuration/TCA/tx_styleguide_inline_mm_child.php
Configuration/TCA/tx_styleguide_inline_mm_childchild.php
Configuration/TCA/tx_styleguide_inline_mn.php
Configuration/TCA/tx_styleguide_inline_mn_child.php
Configuration/TCA/tx_styleguide_inline_mn_mm.php
Configuration/TCA/tx_styleguide_inline_mnsymmetric.php
Configuration/TCA/tx_styleguide_inline_mnsymmetric_mm.php
Configuration/TCA/tx_styleguide_required_flex_2_inline_1_child.php
Configuration/TCA/tx_styleguide_required_inline_1_child.php
Configuration/TCA/tx_styleguide_required_inline_2_child.php
Configuration/TCA/tx_styleguide_required_inline_3_child.php
Configuration/TCA/tx_styleguide_required_rte_2_child.php

TYPO3 master recently moved the language-files.

[TASK] Adjust paths for LLL pointing to EXT:lang

---

Resources/Private/Templates/Styleguide/Buttons.html

The namespace changed and the new name must be used everywhere

Use correct namespace

---

Configuration/TCA/tx_styleguide_elements_basic.php
ext_tables.sql

remove old TCA field none_5 with field fixedRows and set old none_6 to new none_5

[TASK] TCA: remove old none_5 with field fixedRows 

---

Classes/TcaDataGenerator/Generator.php
Classes/TcaDataGenerator/RecordFinder.php
Configuration/TCA/Overrides/pages_language_overlay.php
Configuration/TCA/Overrides/sys_language.php
ext_tables.sql

Prepare the localized data creation.
Create pages_language_overlay's and sys_languages.
Extend delete action for new implementations.
Resolves: #80976

[TASK] Language setup

---

Classes/TcaDataGenerator/RecordFinder.php
Classes/TcaDataGenerator/TableHandler/AbstractTableHandler.php
Classes/TcaDataGenerator/TableHandler/General.php
Classes/TcaDataGenerator/TableHandler/InlineMn.php
Classes/TcaDataGenerator/TableHandler/InlineMnSymmetric.php

Involves comment removal, redundant code removal
and general adaptions.

[TASK] Pre merge fixes

---

ext_emconf.php

[TASK] Update TYPO3 version constraint

---

Configuration/TCA/tx_styleguide_elements_group.php

Core-review to get that fixed in the redirectFinisher is at https://review.typo3.org/54435

recordOverview must be recordsOverview

---

Configuration/TCA/tx_styleguide_elements_group.php
ext_tables.sql

Sys_file_reference is not a mm_table - and we should not use it this way.

[TASK] Remove invalid mm config

---

Configuration/TCA/tx_styleguide_elements_select.php
Resources/Private/Language/locallang.xlf

Resolves: #112 
merge after https://review.typo3.org/c/56689/ has been merged.

[TASK] Provide localized helpText for select_checkbox_3

---

Classes/TcaDataGenerator/Generator.php
Classes/TcaDataGenerator/TableHandler/InlineMnGroup.php
Configuration/TCA/tx_styleguide_inline_mngroup.php
Configuration/TCA/tx_styleguide_inline_mngroup_child.php
Configuration/TCA/tx_styleguide_inline_mngroup_mm.php
ext_tables.php
ext_tables.sql

Hi,
As asked by @tmotyl, here is my sample for inline mn relation using type="group" fields.
Without applying a patch in the core, an warning occurs in file sysext/backend/Classes/Form/Container/InlineControlContainer.php and foreign_unique is ignored.
Thank you,

[TASK] TCA: Add inline mn group example

---

Classes/Controller/StyleguideController.php
Resources/Private/Language/locallang.xlf
Resources/Private/Templates/Styleguide/Modal.html
ext_tables.php

I added examples of using modals

#99 Add modal example

---

Resources/Private/Templates/Styleguide/FlashMessages.html
Resources/Public/JavaScript/RenderNotifications.js

This patch updates the examples of the Notification API to use RequireJS. Also, the freshly introduced action buttons are now used in this example.

[TASK] Update examples of Notification API

---

ext_tables.php

Add missing allowed tables on standard pages

---

Configuration/TCA/tx_styleguide_elements_basic.php

Example for https://forge.typo3.org/issues/90542

[TASK] TCA: Add invertStateDisplay checkbox in flexform

---

Configuration/TCA/tx_styleguide_elements_select.php
ext_tables.sql

This serves as test setup for issue https://forge.typo3.org/issues/91859

[TASK] Add example for selectCheckBox with dividers

---

Configuration/TCA/tx_styleguide_valuesdefault.php
ext_tables.sql

(cherry picked from commit c3e992825c6a5005b760e5678a8552d80a512f0e)

Added checkbox_16 example to valuesdefault

---

Configuration/FlexForms/Simple.xml
Configuration/TCA/tx_styleguide_flex.php
Configuration/TCA/tx_styleguide_palette.php
ext_tables.sql

Flexform examples with the flexform loaded from a file
(cherry picked from commit 42688df04fe9bade089e9848adc5b9f7682beebb)

Added flexform examples for the TCA reference

---

Configuration/TCA/tx_styleguide_elements_group.php
ext_tables.sql

Add example for property hideSuggest for the TCA reference manual
(cherry picked from commit 97d5eb3421d0fba3623d629b23cfa65310ac3f56)

Add group_11, property hideSuggest

---

Classes/TcaDataGenerator/FieldGenerator/TypeSelectRenderTypeSingleForeignTableForType.php
Classes/TcaDataGenerator/FieldGeneratorResolver.php
Configuration/TCA/tx_styleguide_type.php
Configuration/TCA/tx_styleguide_type_foreign.php
Configuration/TCA/tx_styleguide_typeforeign.php
ext_tables.php
ext_tables.sql

Add examples for ctrl-type added in a foreign field, improve ctr-type example for automatic screenshots
(cherry picked from commit e216603c610667d2459dfee966cd42ae8c4c39b9)

Add examples for ctrl-type added in a foreign field

---

Classes/TcaDataGenerator/Generator.php
Classes/TcaDataGenerator/TableHandler/General.php
Configuration/TCA/tx_styleguide_ctrl_common.php
Configuration/TCA/tx_styleguide_ctrl_minimal.php
Resources/Private/Language/locallang.xlf
ext_tables.php
ext_tables.sql

(cherry picked from commit ef8ec38d33ccc46f484f41a18fdd6747d8bfe6d2)

Add examples for minimal and common ctrl definition in TCA

---

Configuration/TCA/tx_styleguide_elements_special.php

custom options already get defined in $GLOBALS['TYPO3_CONF_VARS']['BE']['customPermOptions']['tx_styleguide_custom']

[TASK] Remove todo

---

Configuration/TCA/tx_styleguide_elements_basic.php

Is it ok like this @lolli42? Then I would do the other tables as well

[Task] Task move field info to property 'description'

---

Configuration/TCA/tx_styleguide_elements_select.php
ext_tables.sql

See: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-TCA/issues/273

[Feature] select fields with itemGroups

---

Classes/UserFunctions/FormEngine/SelectItemSorter.php
Configuration/TCA/tx_styleguide_elements_select.php
ext_tables.sql

refs https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-TCA/issues/273

[Feature] #91008 - Item sorting for TCA select items

---

Classes/Controller/StyleguideController.php
Resources/Private/Language/locallang.xlf
Resources/Private/Templates/Styleguide/Accordion.html
ext_tables.php

* Add a example for a simple accordion, all closed, opening independently from each other
* Advanced example, first open, only one open at a time
See #100

[TASK] Add accordion examples

---

Resources/Private/Styles/_components/_example.less
Resources/Private/Templates/Styleguide/Buttons.html
Resources/Public/Css/styles.css

Removes duplicated code and uses
CodeViewHelpers built in example option

[TASK] Remove duplicated code

---

Resources/Private/Templates/Styleguide/Avatar.html

As a styleguide user i expect the preview/example area
to be a representation of the example code below
This brings the preview and code in sync
for the avatar image

[TASK] align avatar preview and code

---

Classes/Controller/StyleguideController.php
Classes/ViewHelpers/CodeViewHelper.php
Resources/Private/Language/locallang.xlf
Resources/Private/Templates/Styleguide/Pagination.html
ext_tables.php

* Adds a fully functional paginated list
* Add example for filter

Add pagination and filter examples

---

Configuration/TCA/tx_styleguide_inline_1n.php
Configuration/TCA/tx_styleguide_inline_expand_inline_1_child.php
Configuration/TCA/tx_styleguide_inline_fal.php
Configuration/TCA/tx_styleguide_inline_mm.php
Configuration/TCA/tx_styleguide_inline_mm_child.php
Configuration/TCA/tx_styleguide_inline_mm_childchild.php
Configuration/TCA/tx_styleguide_inline_mn.php
Configuration/TCA/tx_styleguide_inline_mn_child.php
Configuration/TCA/tx_styleguide_inline_mngroup.php
Configuration/TCA/tx_styleguide_inline_mngroup_child.php
Configuration/TCA/tx_styleguide_inline_mnsymmetric.php

This TCA option is not used by the core since v7 anymore.

[TASK] Remove all showRemovedLocalizationRecords occurrences

---

Build/phpstan.neon
Build/testing-docker/docker-compose.yml
Classes/Command/GeneratorCommand.php
Classes/Controller/BackendController.php
Classes/TcaDataGenerator/AbstractGenerator.php
Classes/TcaDataGenerator/Generator.php
Classes/TcaDataGenerator/GeneratorFrontend.php
Configuration/TypoScript/setup.typoscript
Resources/Private/Forms/simpleform.form.yaml
Tests/Acceptance/Backend/GenerateCommandCest.php
Tests/codeception.yml
composer.json

* Some code cleanup
* Hide root page of frontend by default
* rename write method
⚠️ Depends on https://review.typo3.org/c/Packages/TYPO3.CMS/+/70059

[TASK] Cleanup code

---

Build/phpstan.neon
Classes/TcaDataGenerator/GeneratorFrontend.php
Classes/TcaDataGenerator/RecordFinder.php
ext_tables.sql

Create frontend user and group and
configure it for frontend login.

[TASK] Add frontend user and group

---

README.md

See https://github.com/TYPO3-Documentation/T3DocTeam/issues/161 for details.

[TASK] Update TYPO3 repository URL

---

Configuration/TCA/tx_styleguide_elements_select.php

[BUGFIX] Replace deprecated fileFolder config

---

composer.json

Switch back dev dependencies for core master.
Used commands:
composer req typo3/cms-core:"dev-master" --dev --no-update
composer req typo3/cms-frontend:"dev-master" --dev --no-update
composer req typo3/cms-install:"dev-master" --dev --no-update
composer req typo3/testing-framework:"dev-master" --dev --no-update

[TASK] Prepare main for core master

---

Configuration/TCA/tx_styleguide_elements_basic.php

[TASK] Remove unrelated keys from TCA default value

---

Configuration/TCA/tx_styleguide_elements_select.php

This has been fixed in core with https://forge.typo3.org/issues/96058.

[TASK] Remove resolved todo

---

Classes/Controller/BackendController.php

[BUGFIX] Use correct route identifier for shortcut button

---

Classes/TcaDataGenerator/FieldGenerator/TypeInlineFalSelectSingle12Foreign.php
Tests/Functional/TcaDataGenerator/GeneratorTest.php

Found with using phpstan/phpstan:^1.2.0 temporarly. But makes sense.

[TASK] Minor code cleanup

---

Classes/Controller/BackendController.php
Resources/Private/Templates/Backend/Pagination.html
Resources/Public/JavaScript/Pagination.js

[BUGFIX] Initialize DateTimePicker fields in Pagination example

---

Configuration/TCA/tx_styleguide_elements_select.php

[BUGFIX] Resolve duplicated item value in tx_styleguide_elements_select

---

Tests/Functional/TcaDataGenerator/GeneratorTest.php

Adapt to a patch in typo3/testing-framework,
adding strict typing to functional test case.
Releases: main

[TASK] Adapt to strict FunctionalTestCase

---

Build/Scripts/runTests.sh
Build/phpstan-baseline.neon
Build/phpstan.neon
Build/testing-docker/docker-compose.yml

Instead of manually handling exceptions for phpstan,
baseline handling has been implemented.
Whenever dealing with phpstan for instance when
updating, errors can be handled using
> Build/Scripts/runTests.sh -s phpstanGenerateBaseline

[TASK] Add phpstan baseline handling

---

composer.json

Have latest phpstan in composer.json:
> composer req --dev phpstan/phpstan:^1.4.3

[TASK] Update phpstan:^1.4.3

---

Build/Scripts/runTests.sh
Build/phpstan.neon
Build/testing-docker/docker-compose.yml

composer and phpstan caches in .Build/.cache

[TASK] runTests.sh: HOME, passwd, group mapping is obsolete

---

Build/testing-docker/docker-compose.yml

Simple avoid progress bar in github runs, thus adding corresponding commands.

[TASK] Add options "--no-progress --no-interaction" to phpstan commands

---

Configuration/TCA/tx_styleguide_elements_basic.php
ext_tables.sql

https://review.typo3.org/c/Packages/TYPO3.CMS/+/73816
Fix some other things on the way.
Releases: main

[TASK] Remove "cols" option of type none

---

Classes/Controller/BackendController.php

[BUGFIX] Resolve namespaced arguments in BackendController

---

Build/phpstan-baseline.neon
Classes/Service/KauderwelschService.php
Classes/TcaDataGenerator/FieldGenerator/TypePassword.php
Classes/TcaDataGenerator/FieldGenerator/TypePasswordHashedFalse.php
Classes/TcaDataGenerator/FieldGeneratorResolver.php
Configuration/TCA/tx_styleguide_elements_basic.php
ext_tables.sql

[TASK] Adjust TCA for type=password examples

---

Build/phpstan-baseline.neon
Classes/TcaDataGenerator/FieldGenerator/TypeColor.php
Classes/TcaDataGenerator/FieldGeneratorResolver.php
Configuration/TCA/tx_styleguide_elements_basic.php
Configuration/TCA/tx_styleguide_flex.php
Configuration/TCA/tx_styleguide_inline_1n_inline_1_child.php
Configuration/TCA/tx_styleguide_l10nreadonly.php
Configuration/TCA/tx_styleguide_type.php
Configuration/TCA/tx_styleguide_typeforeign.php
ext_tables.sql

For reference:
* https://review.typo3.org/c/Packages/TYPO3.CMS/+/74121
* https://forge.typo3.org/issues/97271

[TASK] Adjust TCA for type=color examples

---

Configuration/TCA/tx_styleguide_elements_basic.php
Configuration/TCA/tx_styleguide_elements_rte.php
Configuration/TCA/tx_styleguide_inline_1n_inline_1_child.php

Related patch: https://review.typo3.org/c/Packages/TYPO3.CMS/+/74319

[TASK] Adjust TCA for nullable=true

---

.github/workflows/publish.yml
.github/workflows/tests.yml
Build/Scripts/runTests.sh
Build/phpstan-baseline.neon
Build/testing-docker/docker-compose.yml
composer.json

Update phpstan along the way:
> composer req --dev phpstan/phpstan:^1.8.2
> Build/Scripts/runTests.sh -s phpstanGenerateBaseline

[TASK] v11: Add PHP 8.2 to test matrix

---

.github/workflows/tests.yml
Build/Scripts/runTests.sh
Build/testing-docker/docker-compose.yml
Gruntfile.js
Resources/Public/Css/backend.css
Resources/Public/Css/frontend.css
package.json

To avoid css compiling breaks again, we add it to
runTests.sh and run it daily along with other things.
Switch from ruby based sass to node-sass along the way.

[TASK] Add runTests.sh -s buildCss

---

Build/phpstan-baseline.neon
Classes/TcaDataGenerator/FieldGenerator/TypeInputMax4Min4.php
Classes/TcaDataGenerator/FieldGeneratorResolver.php
Configuration/TCA/tx_styleguide_elements_basic.php
ext_tables.sql

https://review.typo3.org/c/Packages/TYPO3.CMS/+/70196

[TASK] Add examples for TCA option "min"

---

Resources/Private/Templates/Content/Login/Login.html

see https://review.typo3.org/c/Packages/TYPO3.CMS/+/74183

[FEATURE] Add CSRF-like request-token to frontend login template

---

Classes/TcaDataGenerator/FieldGenerator/TypeFlex.php
Configuration/FlexForms/Simple.xml
Configuration/TCA/tx_styleguide_displaycond.php
Configuration/TCA/tx_styleguide_elements_basic.php
Configuration/TCA/tx_styleguide_elements_folder.php
Configuration/TCA/tx_styleguide_elements_group.php
Configuration/TCA/tx_styleguide_elements_rte.php
Configuration/TCA/tx_styleguide_elements_select.php
Configuration/TCA/tx_styleguide_elements_t3editor.php
Configuration/TCA/tx_styleguide_flex.php
Configuration/TCA/tx_styleguide_inline_fal.php
Configuration/TCA/tx_styleguide_l10nreadonly.php
Configuration/TCA/tx_styleguide_required.php

https://review.typo3.org/c/Packages/TYPO3.CMS/+/73835

[TASK] Remove "TCEforms" wrapper in FlexForm definitions

---

Classes/Controller/BackendController.php

https://review.typo3.org/c/Packages/TYPO3.CMS/+/74925

[TASK] Avoid using AbstractMessage constants

---

Configuration/TCA/tx_styleguide_required.php

[TASK] Fix some missed required TCA migrations

---

Build/Scripts/runTests.sh
Build/testing-docker/docker-compose.yml

[TASK] Minor cleanups

---

Build/FunctionalTests.xml
Build/UnitTests.xml
composer.json

Brings phpunit 10 as well
> composer req --dev codeception/module-webdriver:^4.0 -w

[TASK] Req --dev codeception/module-webdriver:^4.0 -w

---

composer.json

Used command(s):
```shell
composer req --dev --no-update \
"typo3/cms-core":"~13.0@dev" \
"typo3/cms-frontend":"~13.0@dev" \
"typo3/cms-install":"~13.0@dev" \
"typo3/testing-framework":"dev-main"
composer config \
extra.branch-alias.dev-main "13.x.x-dev"
```
Releases: main

[TASK] Prepare main branch for TYPO3 13.0@dev

---

Configuration/TCA/tx_styleguide_elements_basic.php

Should also go in v12 compat branch.
Fixes: #351

[TASK] Add TCA fields for dbType=time and more examples

---

Build/php-cs-fixer/config.php
Classes/Controller/BackendController.php
Classes/Exception.php
Classes/TcaDataGenerator/Exception.php
Classes/TcaDataGenerator/GeneratorNotFoundException.php
composer.json

Nightly got red. Raise php-cs-fixer, update
ruleset and apply cgl fixes.
> composer req --dev friendsofphp/php-cs-fixer:^3.27
> Build/Scripts/runTests.sh -p 8.1 -s cgl

[TASK] Require friendsofphp/php-cs-fixer:^3.27

---

Build/php-cs-fixer/config.php
Classes/Controller/BackendController.php
Classes/Exception.php
Classes/TcaDataGenerator/Exception.php
Classes/TcaDataGenerator/GeneratorNotFoundException.php
README.md
Tests/Acceptance/Backend/ModuleCest.php
composer.json

Nightly got red. Raise php-cs-fixer, update
ruleset and apply cgl fixes.
> composer req --dev friendsofphp/php-cs-fixer:^3.27
> Build/Scripts/runTests.sh -p 8.1 -s cgl

[TASK] Require friendsofphp/php-cs-fixer:^3.27 (#432)

---

Configuration/TCA/tx_styleguide_elements_basic.php
ext_tables.sql

And change existing ext_tables.sql
definitions to sane values.

[TASK] TCA: Add nullable color example

---

Classes/TcaDataGenerator/FieldGenerator/TypeFlex.php

https://review.typo3.org/c/Packages/TYPO3.CMS/+/81418

[TASK] Avoid second argument to flexArray2Xml()

---

Resources/Private/Partials/Backend/Navigation.html
Resources/Private/Templates/Backend/Pagination.html

[TASK] Apply lintHtml changes

---

Classes/TcaDataGenerator/AbstractGenerator.php

Resource\Enum\DuplicationBehavior instead of
Resource\DuplicationBehavior, see
https://review.typo3.org/c/Packages/TYPO3.CMS/+/79568

[TASK] Adapt DuplicationBehavior usage

---

Build/phpstan-baseline.neon
Build/testing-docker/docker-compose.yml
Classes/TcaDataGenerator/Generator.php
Classes/TcaDataGenerator/RecordFinder.php

This is actually most likely a phpstan bug.
We add an @var hint to circumvent.

[TASK] Fix a last phpstan error on this level

---

Classes/Controller/BackendController.php
Resources/Private/Styles/backend.scss
Resources/Private/Templates/Backend/Accordion.html
Resources/Private/Templates/Backend/Avatar.html
Resources/Private/Templates/Backend/Buttons.html
Resources/Private/Templates/Backend/Cards.html
Resources/Private/Templates/Backend/Colors.html
Resources/Private/Templates/Backend/Filter.html
Resources/Private/Templates/Backend/FlashMessages.html
Resources/Private/Templates/Backend/Icons.html
Resources/Private/Templates/Backend/Index.html
Resources/Private/Templates/Backend/Infobox.html
Resources/Private/Templates/Backend/Modal.html
Resources/Private/Templates/Backend/Notifications.html
Resources/Private/Templates/Backend/Pagination.html
Resources/Private/Templates/Backend/Tab.html
Resources/Private/Templates/Backend/Tables.html
Resources/Private/Templates/Backend/Trees.html
Resources/Private/Templates/Backend/Typography.html
Resources/Public/Css/backend.css

Have a unique BE css id to restrict any
declared CSS to the styleguide module.

[TASK] Namespace BE css
