TYPO3-CMS/styleguide

Configuration/TCA/tx_styleguide_forms_inline_2_child1.php
ext_tables.sql

Testcase for a select with renderMdoe=tree inside an IRRE element.
At the moment only the first select (inline_3) will be displayed and the second one (inline_4) will vanish. If you change the order of the fields, the same happens: inline_4 will be "dsplayed" and inline_3 not. 
As requested in Ticket https://forge.typo3.org/issues/68013

[TASK] Adds inline tree selector example

---

Resources/Private/Layouts/Default.html

since prototype is not part of the TYPO3 core, the argument was removed.

[TASK] Remove loadPrototype argument

---

ext_tables.sql

TCA contains a definition of inline4 field, but it's missing in the sql. which caused sql error on saving

Add missing inline_4 sql definition for styleguide_form

---

ext_tables.sql

Add missing field to ext_tables.sql to enable saving test records of inline collapse/expand tests.

[BUGFIX] Add dummy_1 field to tx_styleguide_inlineexpand_inline_1_child1

---

Configuration/TCA/tx_styleguide_forms.php
ext_tables.sql

Add an example of a group field with internal type of `folder`. See https://docs.typo3.org/typo3cms/TCAReference/Reference/Columns/Group/Index.html#internal-type for reference.

[TASK] Add example for type=group, internal_type=folder

---

Configuration/Flexform/Flex_3.xml

Fix the spelling of XML elements for foreign_label and foreign_selector

[BUGFIX] Flexform inline_2 FAL record config

---

composer.json
ext_emconf.php

The following error occurs in TYPO3 7.6.0 when you hit the form engine test button:
> TCA internal_type of field "group_13" in table tx_styleguide_forms must be set to either "db", "file" or "file_reference"
This is the result of the following [Bug #70449](https://forge.typo3.org/issues/70449) which has been fixed with the release of TYPO3 7.6.1.

[TASK] Set minimum TYPO3 version to 7.6.1 due to the use of the TCA type group with internal_type folder

---

Configuration/TCA/tx_styleguide_elements_basic.php
ext_tables.sql

Using bootstrap based color-picker via "renderType" instead of
wizard type "colorbox" now and removing the custom image picking.
Related: https://forge.typo3.org/issues/73728

[TASK] Adjust color-picker widget to new render-type

---

Configuration/TCA/tx_styleguide_elements_basic.php
ext_tables.sql

Creating data throws errors in strict mode as text/blob fields
can't have a default value but no data is given and they are defined
as "NOT NULL".
Additionally this fixes the definition of radio_6, which is an int field.

[TASK] Remove unneccessare NOT NULL constraints

---

ext_tables.sql

MySQL 5.7.8+ have included NO_ZERO_DATE/NO_ZERO_IN_DATE in the strict
mode settings and have strict mode enabled as default. The default
values of 0000-00-00 and 0000-00-00 00:00:00 are incompatible with
that setting and trigger SQL errors when inserting data or creating
the table.

[BUGFIX] Remove invalid default values from input_36/input_37

---

Configuration/TCA/tx_styleguide_elements_select.php
ext_tables.sql

- Remove not used allowRecursiveMode and width settings.
- Improve labels.
- Fix misplaced expandAll setting
- Add tree with requestUpdate setting
- Add tree with readOnly=true

Tune selectTree examples

---

Configuration/TCA/tx_styleguide_valuesdefault.php
ext_tables.sql

There is currently a bug in the core preventing the field from being
saved with no value selected.

[TASK] Add an example for a selectCheckBox field with multiple defaults

---

Classes/TcaDataGenerator/Generator.php
Classes/TcaDataGenerator/RecordFinder.php
Configuration/TCA/Overrides/sys_language.php
ext_tables.sql

The pages_language_overlay part of delete action is unnecessary.
This means the recordfinder function for the overlays is also unneeded.

[TASK] Review fixes and adaptions

---

ext_tables.php

This fixes the problem, that styleguide removes permissions from all other extensions due to overwriting the whole array

[BUGFIX] allow multi extension permissions

---

Resources/Private/Templates/Styleguide/Tables.html

Instead of using `t3-table` use the class `table`

[BUGFIX] Use correct class for table

---

Configuration/TCA/tx_styleguide_inline_1nnol10n.php
Configuration/TCA/tx_styleguide_inline_1nnol10n_child.php
ext_tables.php
ext_tables.sql

The not translatable status is also marked with `'l10n_mode' => 'exclude'` in the parent records TCA.

[FEATURE] TCA record for inline 1n with a not translatable child

---

Configuration/TCA/tx_styleguide_inline_11.php
Configuration/TCA/tx_styleguide_inline_11_child.php
ext_tables.php
ext_tables.sql

Example code for reproducing issue https://forge.typo3.org/issues/82121

Provide inline 1:1 example with relation field on the parent side

---

Configuration/TCA/tx_styleguide_elements_select.php

This allows testing the behaviour of this field in a translated element.
---
The main goal of this change is to be able to test this ticket: https://forge.typo3.org/issues/82843

[TASK] Set l10n display setting to `defaultAsReadonly` for select

---

Classes/Controller/StyleguideController.php
Resources/Private/Styles/_components/_icon.less
Resources/Private/Templates/Styleguide/Icons.html
Resources/Public/Css/styles.css
package.json

Renders deprecated icons of IconRegistry.
Relies on https://review.typo3.org/#/c/55829/ for TYPO3 v9

[FEATURE] Render deprecated icons

---

Classes/TcaDataGenerator/TableHandler/AbstractTableHandler.php
Classes/TcaDataGenerator/TableHandler/General.php

Instead of direct sql inserts and updates.
It comes with some performance penalty,
generation time with patch:
1) 21.941178798676
2) 26.553791999817
Without the patch:
1) 20.42106294632
2) 21.038254022598
Note that this patch doesn't replace all direct inserts, but just one in General Table Handler.

Use DataHandler commands to create and update data for General Handler

---

Configuration/TCA/tx_styleguide_elements_select.php

It is not in use since v7 at last.
see corresponding change in docs:
https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-TCA/pull/195

Remove select field 'rootLevel' property

---

Configuration/TCA/tx_styleguide_elements_select.php
ext_tables.sql

this commit adds an example TCA field for a select field with renderType = selectMultipleSideBySide and maxitems = 1.
see also:
https://review.typo3.org/#/c/58599/
https://forge.typo3.org/issues/86594

add example select multipleSideBySide maxitems=1

---

Configuration/TCA/tx_styleguide_inline_parentnosoftdelete.php

The special handling of this DB field is dropped in TYPO3 core v10
https://review.typo3.org/#/c/59297/

[TASK] Remove t3ver_label usage

---

ext_tables.php

Defining the vendor name yourself (TYPO3.CMS) and using a controller alias ('Styleguide') instead of the FQCN is deprecated since TYPO3 10.4, therefore the module registration must be changed.

Update module registration arguments

---

Tests/Acceptance/Support/Extension/BackendStyleguideEnvironment.php

testing-framework provides a fixture file for backend user
sessions - used to log in users during acceptance tests.
Core v11 however changed db structure of the table:
ses_backupserid is gone. The fixture still tries to set
this, leading to db errors on insert. Solution in
v11 styleguide for to use the fixture provided by
ext:core, instead of the TF version, until the situation
has been solved in testing-framework.

[BUGFIX] be_sessions.xml fixture from ext:core instead of TF

---

Configuration/TCA/tx_styleguide_valuesdefault.php
ext_tables.sql

empty default value selects none, radio buttons get selected by value, example where the value and ordal number are not the same to reduce confusion
(cherry picked from commit 46fbe22a2d3e9ae90613eba7f2c45a7d124192e5)

Default examples for radiobuttons

---

Configuration/TCA/tx_styleguide_type.php
ext_tables.sql

Improve record type example. rename column "type" to column "record_type" for more clarity. 
Introduce examples for using a different set of fields
'type' => 'type' isn't so easy to understand in the manual...
(cherry picked from commit adf77dd51f4797de655f474ef8044a43302535c2)

Improve example for type

---

Configuration/TCA/tx_styleguide_elements_rte.php
ext_tables.sql

Richtext configurations for RTE using "minimal" and "full" configurations
(cherry picked from commit 0bccbfb39a543d67e4976ca9d1fdb09db84e7bcd)

Add examples for richtextConfigurations

---

Configuration/TCA/tx_styleguide_flex.php

add flex form examples for for checkbox_2 and checkbox_12 from to be used in the tca reference manual
(cherry picked from commit 1c40c72ea7a7c4934547f093acd5074f542e31c2)

Add flex examples checkboxes

---

Configuration/TCA/tx_styleguide_elements_basic.php

InputLinks are opened with a modal instead of a new popup window.
This option has no effect here anymore.

Remove windowOpenParameters option in inputLink

---

Configuration/TCA/tx_styleguide_elements_select.php

There aren't many places left where popups are opened
with new windows. These are edit popups for select records
with selectMultipleSideBySide as renderType for example.

[TASK] Add working windowOpenParameters example

---

Classes/TcaDataGenerator/FieldGenerator/TypeTextWizardTable.php

The input values do not use correct values
according to their position in the table.
Changed the content generator to put
the right values in each row/column.

[BUGFIX] Use correct naming for cell values

---

Build/Scripts/runTests.sh
Build/testing-docker/docker-compose.yml

Changed syntax of docker-compose.yml to be compatible
with v2.0 and set composer home directory to make
sure source install will work.

[TASK] Fix testing for MacOS and docker-compose 2

---

Configuration/TCA/tx_styleguide_elements_basic.php
ext_tables.sql

This allows us to test saving empty dates with a lower range set to
the current time. This is used for example in the endtime field for
pages and tt_content.

[TASK] Add additional example for inputDateTime with range set

---

.github/workflows/tests.yml
Build/Scripts/runTests.sh
Build/testing-docker/docker-compose.yml

When installing the test environment and having no composer.lock,
'composer update' should be used instead of 'composer install'.

[TASK] runTests.sh: Use composer update instead of install

---

composer.json

That test related helper class reference in
composer.json is obsolete in v11.
https://review.typo3.org/c/Packages/TYPO3.CMS/+/71029
https://forge.typo3.org/issues/94996

[TASK] Avoid ExtensionTestEnvironment::prepare

---

Configuration/TCA/tx_styleguide_elements_group.php
Configuration/TCA/tx_styleguide_elements_select.php
Configuration/TCA/tx_styleguide_inline_usecombination.php

The option autoSizeMax is a common property between select, group and
inline fields. This patch adds examples for group and inline fields.
Inline fields have to fulfill special conditions for autoSizeMax
to be useful:
1. foreign_selector has to be defined.
2. The field, foreign_selector is pointing to, has to be of type select.
Only then a select field is rendered, which autoSizeMax can be applied
to.
Also increase the minimum value to at least 10 or else no effect will be
visible because of a css min-height of 156px in TYPO3 v11. This equals
~7 rows depending on the browser.

[TASK] Add additional autoSizeMax examples for type group and inline

---

composer.json

Update dependencies to match v11 core development to get
tests green again. This is done as preparation to split
branch for v11. Composer package sorting is added as a
sideway change.
Note: 'typo3/cms-about' is removed as dependency as
this has been merged to 'typo3/cms-backend'.
After branching dependencies should be set to match current
core master development.
This gets the tests green.
Used commands:
composer config sort-packages true
composer rem typo3/cms-about --dev --no-update
composer req typo3/cms-core:"11.*.*@dev" --dev --no-update
composer req typo3/cms-frontend:"11.*.*@dev" --dev --no-update
composer req typo3/cms-install:"11.*.*@dev" --dev --no-update
composer req typo3/testing-framework:"^6.14.0" --dev --no-update

[TASK] Set dependency for v11 as branching preparation

---

.github/workflows/tests.yml
Build/Scripts/runTests.sh

Run casual tests, but disable php-cs-fixer with
8.1 for now since it is not yet compatible.

[TASK] Run tests with PHP 8.1

---

Build/Scripts/runTests.sh
Build/testing-docker/docker-compose.yml

docker on mac and windows WSL2 encapsulate a VM into
the system. The current xdebug remote config does not
work in those cases since the host IP can not be
determined with the current solution.
Switching to host.docker.internal works for macOS
and WSL2, and works for linux too in combination with
an extra_hosts setting.
This requires linux to use at least docker 20.10,
which shouldn't be a huge issue with casual developer
machines.
Adopted from:
https://review.typo3.org/c/Packages/TYPO3.CMS/+/72194

[TASK] runTests.sh: xdebug trigger works with macOS and WSL2

---

Classes/Form/Element/User1Element.php

PR #255 unfortunately used wrong array index,
it should have been `itemFormElValue`.

[BUGFIX] Use correct itemFormElValue

---

composer.json

Instead of requireing a named branch, the semantically correct
version is required and a branch alias is added, so that
this package can also be required using a version.

Set version contraints for TYPO3 packages

---

.github/workflows/tests.yml
Build/testing-docker/docker-compose.yml
Configuration/TCA/Overrides/fe_groups.php
Configuration/TCA/Overrides/fe_users.php
ext_tables.sql

First we change ext_tables.sql to fix an issue, not detecting styleguide
records correctly in 'fe_users' and 'fe_groups'.
Secondly we enable postgres acceptance testing, as this failed because
of the error which first commit has fixed.
Fourth, we revert the chrome driver raise as it seems that the raised
version is unstable for styleguide, when run as github action.
Last but not least, we add missing TCA for fe_users and fe_groups.

[BUGFIX] Frontend user and groups & acceptance postgres & chrome revert

---

Classes/TcaDataGenerator/RecordFinder.php
Tests/Functional/TcaDataGenerator/GeneratorTest.php

Records has been created with the pid of a translated page,
not with the default language pid when executed with sqlite.
That came from the RecordFinder->findPidOfMainTableRecord()
method, which was not updated after page overlays had been
removed from the core. Many dbms and version automatically
adds a deterministic sorting criteria, if sorting would be
not deterministic - but not all.
This commit adds deterministic sorting to that method, filters
for default language only, which is what is wanted. Furthermore
generator test is adjusted to check not only for record count,
but if they are created on the correct page, at least for one
example data table.
Last but not least this commit replaces fetchColumn() with
fetchOne() in GeneratorTests as a preparation for doctrine/dbal
raise in the …

[BUGFIX] Ensure records are created with correct pid with sqlite

---

Build/phpstan.neon
Classes/Form/Element/User1Element.php

This pull-requests contains two fixes to get the pre-merge and thus
the scheduled nightly for main branch green again, as it can be seen
here: https://github.com/sbuerk/styleguide/actions/runs/1697288968
- Remove unneded phpstan ignore configuration (fixed in core )
- Set correct method docblock to make phpstan happy again
These changes should not be backported for now. Adjustments for branch
11 and 10 will be provided in dedicated pull-requests, as they need
different and not fully solvable in the same way for now.

[BUGFIX] Ensure scheduled and pre-merge tests are happy again

---

Build/phpstan.neon

Adjust ignore pattern in phpstan configuration to ignore the updated
broken docblock of QueryBuilder::orWhere() in core with 11.5.5, and
add an todo to remove this after 11.5.6 release where this is fixed
correctly in core and makes the ignore pattern superflous.
See: https://github.com/sbuerk/styleguide/actions/runs/1697349484

[BUGFIX] Adjust phpstan ignore pattern configuration

---

composer.json

composer 2.2.x checks if plugins are allowed, and if not asks for
confirmation to execute (and add) it.
This change adds the needed allowed plugins to composer.json, which
ensures tests can still run if composer version in core testing images
is raised.
Releases: main, 11, 10

[TASK] Add allowed plugins to composer.json

---

Build/phpstan.neon

PHPStan configuration option 'excludes_analyse' is deprecated and
should be replaced with the new option 'excludePaths' which would
prepare for PHPStan version raise. At least this suppress the
deprecation notice on phpstan execution.
Added a todo comment for option 'checkMissingIterableValueType'
why this is needed and when to recheck and remove along the way.
Readings:
https://gitanswer.com/rector-prepare-for-phpstan-1-0-1026148998 (BC breaks for end-users)
https://github.com/phpstan/phpstan-src/commit/d25c5e5a6c62a4537d4a108707ff26b5bea687d9

[TASK] Avoid deprecated phpstan configuration 'excludes_analyse'

---

Build/testing-docker/docker-compose.yml
Tests/Acceptance/Fixtures/be_sessions.xml
Tests/Acceptance/Support/Extension/BackendStyleguideEnvironment.php

This pull-requests fix the github ci testing for branch 10,
which was broken due an incompatible updated fixture file
in testing_framework. Additional it adds acceptance xdebug
debugging ability to this branch as a follow up.

[BUGFIX] Ensure acceptance tests works again on v10 branch

---

Build/phpstan.neon

This change removes the discouraged usage of '%currentWorkingDirectory%'
throughout the phpstan configuration.
See: https://phpstan.org/config-reference#expanding-paths

[TASK] Avoid '%currentWorkingDirectory%' in phpstan configuration

---

Configuration/TCA/tx_styleguide_elements_rte.php

Since the introduction of ckeditor, this fieldControl
is not available anymore. The fullscreen option is
controlled in the editor yaml file.

[TASK] Remove obsolete fullScreenRichtext fieldControl

---

Configuration/TCA/tx_styleguide_elements_basic.php
ext_tables.sql

The tableWizard as a fieldControl for the textTable element in gone in
TYPO3 v11:
https://review.typo3.org/c/Packages/TYPO3.CMS/+/70823
Instead, it is always displayed inline. The real textarea field is now
hidden from the user.
Because of that, setting "rows" doesn't make any sense anymore, besides
when using together with "readOnly". Thus, it is removed from the
example.
Along with that "cols", "numNewRows" and "xmlOutput" are no longer
configurable.
The removed field text_21 is not used in TYPO3 acceptance tests, so it
needs no adjustments from that side.
Releases: main, 11.5

[TASK] Remove tableWizard example

---

Classes/TcaDataGenerator/AbstractGenerator.php
Classes/TcaDataGenerator/FieldGenerator/TypeSelectRenderTypeSingleForeignTableForType.php
Classes/TcaDataGenerator/RecordFinder.php
Tests/Functional/TcaDataGenerator/GeneratorTest.php

TYPO3 v12 has deprecated the `QueryBuilder->execute()`
method to align with corresponding deprecation of the used
doctrine/dbal package with:
ISSUE: https://forge.typo3.org/issues/96972
PATCH: https://review.typo3.org/c/Packages/TYPO3.CMS/+/73610
This patch replaces corresponding 'execute()' calls with the
proper replacement method.
Releases: main

[TASK] Replace deprecated QueryBuilder->execute()

---

.editorconfig
Build/phpstan-baseline.neon
Classes/TcaDataGenerator/FieldGenerator/TypeFolder.php
Classes/TcaDataGenerator/FieldGenerator/TypeGroupAllowedBeUsers.php
Classes/TcaDataGenerator/FieldGenerator/TypeGroupAllowedBeUsersBeGroups.php
Classes/TcaDataGenerator/FieldGenerator/TypeGroupAllowedPages.php
Classes/TcaDataGenerator/FieldGenerator/TypeGroupAllowedStaticdata.php
Classes/TcaDataGenerator/FieldGenerator/TypeGroupAllowedSysFiles.php
Classes/TcaDataGenerator/FieldGenerator/TypeGroupFal.php
Classes/TcaDataGenerator/FieldGeneratorResolver.php
Configuration/TCA/tx_styleguide_elements_folder.php
Configuration/TCA/tx_styleguide_elements_group.php
ext_tables.php
ext_tables.sql

As a result of:
https://review.typo3.org/c/Packages/TYPO3.CMS/+/73622
internal_type=folder is now an own type (=folder).
Also editorconfig is adjusted to the current style.
Releases: main

[TASK] Add type=folder examples

---

Build/testing-docker/docker-compose.yml
Configuration/TCA/tx_styleguide_ctrl_common.php
Configuration/TCA/tx_styleguide_inline_mm.php
Configuration/TCA/tx_styleguide_inline_mm_child.php
Configuration/TCA/tx_styleguide_inline_mm_childchild.php
Configuration/TCA/tx_styleguide_inline_mn.php
Configuration/TCA/tx_styleguide_inline_mn_child.php
Configuration/TCA/tx_styleguide_inline_mngroup.php
Configuration/TCA/tx_styleguide_inline_mngroup_child.php
Configuration/TCA/tx_styleguide_inline_mnsymmetric.php
Configuration/TCA/tx_styleguide_inline_mnsymmetricgroup.php
Configuration/TCA/tx_styleguide_required.php
Configuration/TCA/tx_styleguide_required_flex_2_inline_1_child.php
Configuration/TCA/tx_styleguide_required_inline_2_child.php
Configuration/TCA/tx_styleguide_required_inline_3_child.php
Configuration/TCA/tx_styleguide_required_rte_2_child.php

Pull request contains two commits
**[BUGFIX] Avoid deprecated TCA eval option "required"**
This change adopts the corresponding TCA definition
changes to avoid the TCA auto migration warning and
github ci failures.
See: https://forge.typo3.org/issues/97035
Releases: main
and 
**[TASK] Add options "--no-progress --no-interaction" to phpstan commands**
backport of provided with https://github.com/TYPO3/styleguide/pull/300 .

[BUGFIX] Avoid deprecated TCA eval option "required"

---

README.md

See https://github.com/TYPO3-Documentation/T3DocTeam/issues/170 for details.

[TASK] Fix outdated TYPO3 installation documentation URL

---

Configuration/TCA/tx_styleguide_elements_basic.php

While migrating the TCA for the new type
"datetime", the FlexForm part has been
forgotten.

[TASK] Migrate datetime TCA of FlexForm

---

Configuration/TypoScript/constants.typoscript

ext:styleguide provides the ability to create a frontend page tree
with proper site configuration. Because of included indexed_search
example, the indexed search TypoScript setup file is included into
the frontend site TypoScript configuration. However, the similar
include for the constants part has been missed, which is the reason
that the list/indexed_search example does not work out of the box,
if indexed_search extension is installed.
This change adds the corresponding constant import to the frontend
constant TypoScript setup to mitigate this issue and let the example
work out of the box, as long as ext:indexed_search is installed.
Fixes: #321 for main

[BUGFIX] Include TypoScript constants of indexed_search in frontend site configuration (main)

---

Configuration/TypoScript/constants.typoscript

ext:styleguide provides the ability to create a frontend page tree
with proper site configuration. Because of included indexed_search
example, the indexed search TypoScript setup file is included into
the frontend site TypoScript configuration. However, the similar
include for the constants part has been missed, which is the reason
that the list/indexed_search example does not work out of the box,
if indexed_search extension is installed.
This change adds the corresponding constant import to the frontend
constant TypoScript setup to mitigate this issue and let the example
work out of the box, as long as ext:indexed_search is installed.
Fixes: #321 for 11, prepared backport/cherry pick of PR #322
Note: Needs at least a tag / release so we can add it properly to v11 core …

[BUGFIX] Include TypoScript constants of indexed_search in frontend site configuration (11)

---

Build/Scripts/runTests.sh
Build/testing-docker/docker-compose.yml

Currently, selenium does not support arm64.
A condition was added to detect arm64 and use "seleniarm/standalone-chromium" image if running on arm64.

[BUGFIX] Switch to seleniarm/standalone-chromium for arm64 arch.

---

Configuration/Yaml/FormSetup.yaml

Even if styleguide is installed it must be possible to generate custom forms in fileadmin

[BUGFIX] Allow custom forms

---

Tests/Functional/TcaDataGenerator/GeneratorTest.php

This gets the type annotation in line with the latest testing
framework changes and fixes a PHPStan warning.
Releases: main, 11, 10

[BUGFIX] Make a type annotation in a test more specific

---

Configuration/Yaml/FormSetup.yaml

The namespace `TYPO3.CMS.Form` in form configuration was removed with TYPO3/typo3@451c896. With this patch, the appropriate form configuration has been adapted to follow the new recommendations.
Related: #97517
Releases: main

[TASK] Remove superfluous namespace within form configuration

---

README.md

Information about how to initialize the pages is added
to the README. This includes the command line arguments
but also introduces the styleguide module in the backend
which was previously not mentioned in the README.
----
Not in commit message: I noticed, this information is missing. Also this results in this being documented elsewhere which is not ideal, because it would be best to refer to the documentation in the extension, see
* Contrib Guide: https://docs.typo3.org/m/typo3/guide-contributionworkflow/main/en-us/Setup/UseStyleguide.html
* TCA: https://docs.typo3.org/m/typo3/reference-tca/main/en-us/Examples/StyleGuide.html

Add instructions to the README

---

Classes/Controller/BackendController.php

The php enum ContextualFeedbackSeverity is added in TYPO3 12.0. Replace
usages of the deprecated FlashMessage constants with the new enum.

[TASK] Use ContextualFeedbackSeverity instead of deprecated constants

---

.github/workflows/tests.yml
Build/Scripts/runTests.sh
Build/testing-docker/docker-compose.yml

Use specific github error formatting for phpstan
error reporing in github actions. This adds the
phpstan errors directly into the file view on pull
requests for better readability.
For direct pushes
on commit level it directly extracts and shows the
errors in the pane instead of only in the command
line view.
Releases: main, 11, 10

[TASK] Use phpstan github error format in github actions

---

Resources/Private/Templates/Backend/Icons.html
ext_tables.php

FontAwesome is subject of removal in TYPO3 v12. This commit removes all
usages of FontAwesome from templates and ext_tables.php.

[TASK] Drop FontAwesome usages

---

ext_tables.sql

Text fields don't need a default value, and dropping this one
solves an issue with a changed DB field schema definition raised
in doctrine/dbal version 3.4.0.
It is the only text field with default value both in ext:styleguide
and in TYPO3 Core, so it is probably safe to remove the default value
and leave the handling of text fields inside database systems to
doctrine/dbal.

[TASK] Drop default value for text field

---

Configuration/Icons.php
ext_tables.php

As introduced here https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.4/Feature-94692-RegisteringIconsViaServiceContainer.html
resolves #349

Register Icons in Icons.php

---

Configuration/TCA/tx_styleguide_elements_group.php

The field `pages.alias` is removed for quite some but still used for the search in field `group_db_10`. The usage of said field is now removed.

[BUGFIX] Drop removed field "alias"

---

.gitignore
composer.json

TYPY3v12 recently added hard requirement for `typo3/cms-composer-installers:5.x`, which install core system extensions and extensions in a different way. This breaks how typo3/testing-framework expects the existing structure to work for unit, functional and acceptance tests.
Until the final overwork for the testing-structure is implemented, the intermediate solution in form of a composer plugin is used, which basicly provides through symlinks the expected structure.
This *must* and will be vanish in the future or replaced by the official way.
Used command(s):
```shell
$ composer require --dev \
sbuerk/typo3-cmscomposerinstallers-testingframework-bridge:^0.0.1
```

[BUGFIX] Ensure testing works with CMSComposerInstallers 5

---

.github/workflows/tests.yml

GitHub has deprecated node v12 support for executing GitHub actions. This currently adds corresponding deprecation note to action results, also not failing for now.
This change updates action/checkout to use v3 instead of v2 to use Node v16 compatible version and thus avoiding the deprecation notice.
See: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

[TASK] Upgrade action/checkout to avoid deprecation message

---

composer.json

With v12.1 branching and releases, styleguide now
preferred 12.1 tags in it's testing dependencies.
Force ~12.2@dev to trigger dev-main core deps again.
composer req --dev typo3/cms-core:~12.2@dev \
typo3/cms-frontend:~12.2@dev \
typo3/cms-install:~12.2@dev

[BUGFIX] styleguide uses core dev-main for --dev

---

Classes/TcaDataGenerator/AbstractGenerator.php

Clearing in BE context otherwise confuses
extbase BackendConfigurationManager after
deleting page tree.

[BUGFIX] Generator clears caches on CLI only

---

Classes/TcaDataGenerator/FieldGenerator/TypeRadio.php
Classes/TcaDataGenerator/FieldGenerator/TypeSelect.php

This is a preparation patch for the upcoming switch to associated items array keys. The default value generators for select and radio are adjusted to work for both variants, so tests for the mentioned patch can go green.
Related patch: https://review.typo3.org/c/Packages/TYPO3.CMS/+/77626
Releases: main

[TASK] Compatibility with associated array keys for TCA items

---

composer.json

Raise from 12.2@dev to 12.3@dev forces dev-main.

[TASK] styleguide uses core dev-main for --dev

---

Build/Scripts/runTests.sh
Build/testing-docker/docker-compose.yml

This change adjusts `Build/Scripts/runTests.sh` and
`Build/testing-docker/docker-compose.yml` to add a
docker image prefix. This prefix is hardcoded to use
the TYPO3 core-testing images from the TYPO3 GitHub
Container Registry by setting the prefix to `ghcr.io`.

[TASK] Use core-testing-* images from `ghcr.io`

---

Build/UnitTestsBootstrap.php
Build/testing-docker/docker-compose.yml
composer.json

This change raises to testing-framework ^8.0.0. The now obsolete
"sbuerk/typo3-cmscomposerinstallers-testingframework-bridge"
is removed again and necessary configuration changes applied.    
Used command(s):
```shell
composer remove --dev --no-update \
"sbuerk/typo3-cmscomposerinstallers-testingframework-bridge"
composer require --dev --no-update \
"typo3/testing-framework":"^8.0"
```

[TASK] Use typo3/testing-framework 8.x.x

---

Resources/Private/Styles/frontend.scss
Resources/Public/Css/backend.css
Resources/Public/Css/frontend.css

The build of SCSS failed due to missing variable $primary-text-emphasis-dark
which is required for darkmode. Darkmode is now enabled by default in bootstrap.
The bootstrap module _variables-dark should be imported.
Since further changes are necessary for darkmode to fully work, we disable the
mode for now.
Resolves: #390

[TASK] Disable darkmode for Frontend

---

Resources/Private/Templates/Backend/Avatar.html
Resources/Private/Templates/Backend/Filter.html
Resources/Private/Templates/Backend/Icons.html
Resources/Private/Templates/Backend/Infobox.html
Resources/Private/Templates/Backend/Tca.html
Resources/Private/Templates/Backend/Typography.html

With v12 the p.lead was removed and should therefore no longer be used.

[TASK] Remove lead class from introductory paragraphs and code example

---

ext_emconf.php

This change sets the version in the `ext_emconf.php`
to the next version, matching the current TYPO3 core
main branch version.

[TASK] Set correct core version in `ext_emconf.php`

---

Classes/TcaDataGenerator/FieldGenerator/TypeDatetimeFormatTime.php
Classes/TcaDataGenerator/FieldGenerator/TypeDatetimeFormatTimesec.php

The database generator does not use the DataHandler for
all operation due to some performance considerations.
That means, that special handlings included in DataHandler
needs to be adopted - at least in a stripped down version.
For example, the DataHandler contains value transformation
for `type = datetime` when the `dbType` is one of following
types: `datetime`, `time`, `timesec`.
Until now, now records are created with this constellation.
To be able to add such fields in the future, we need to mimic
partly work done by the DataHandler for these type in record
generation.
Releases: main, 12

[BUGFIX] Generate correct values for `datetime` type fields

---

Resources/Private/Templates/Backend/Icons.html
Resources/Private/Templates/Backend/Index.html
Resources/Public/JavaScript/processing-indicator.js
Tests/Acceptance/Backend/ModuleCest.php

This change replaces the obsolete "Font Awesome Icons"
markup on the icon search page and in the section to
create example page trees with TCA demo records and
content elements.
JavaScript selectors are adjusted to match the changed
markup.
The spinner is changed from dark as a side-change for
a cleaner user experiance and aligns to a recently core
patch [1].
[1] https://review.typo3.org/c/Packages/TYPO3.CMS/+/80103
Resolves: #416
Releases: main, 12

[TASK] Replace obsolete Font Awesome icons (main)

---

Resources/Private/Templates/Backend/Icons.html
Resources/Private/Templates/Backend/Tca.html
Resources/Public/JavaScript/processing-indicator.js
Tests/Acceptance/Backend/ModuleCest.php

This change replaces the obsolete "Font Awesome Icons"
markup on the icon search page and in the section to
create example page trees with TCA demo records and
content elements.
JavaScript selectors are adjusted to match the changed
markup.
The spinner is changed from dark as a side-change for
a cleaner user experiance and aligns to a recently core
patch [1].
[1] https://review.typo3.org/c/Packages/TYPO3.CMS/+/80103
Resolves: #416
Releases: main, 12

[TASK] Replace obsolete Font Awesome icons (12)

---

Classes/Controller/BackendController.php
Classes/ViewHelpers/CodeViewHelper.php
Resources/Private/Language/locallang.xlf
Resources/Private/Templates/Backend/Cards.html

TYPO3 uses cards in the install tool as a valid backend component.
This change adds them to the styleguide as example for extension
developers and how to use them.
Resolves: #359
Releases: main, 12

[TASK] Add a page for card component with instructions and examples

---

Configuration/TCA/tx_styleguide_inline_mm.php
Configuration/TCA/tx_styleguide_inline_mm_child.php
Configuration/TCA/tx_styleguide_inline_mm_childchild.php

This config is not needed for those tables and
will become obsolete with TYPO3 v13.
Releases: main

[TASK] Avoid TCA MM_hasUidField

---

ext_tables.sql

We're adding core code to add default sql definitions derived from TCA. As a starter type=file does not need to be set anymore. One case is left that needs another core patch, though.
Releases: main
Related: https://forge.typo3.org/issues/101571

[TASK] Remove all type=file sql field definitions

---

ext_tables.sql

DB fields for TCA types category, datetime and
slug are auto-created since v12, they can be
removed from ext_tables.sql.

[TASK] Remove a series of ext_tables.sql defs

---

README.md
Tests/Acceptance/Backend/ModuleCest.php

Some acceptance tests tends to produce errors
in the JavaScript console. This can be mitigated
by using a higher waitTime for `useExistingSession`.
Additionally, missing badges are added to the
README.md file.
Releases: main

[TASK] Stabilize acceptance tests

---

Configuration/TCA/tx_styleguide_elements_basic.php
ext_tables.sql

We're adding core code to add default sql definitions derived from TCA. Fields of type=email do not need to be set anymore.
Releases: main
Related: https://forge.typo3.org/issues/101654

[TASK] Remove all type=email sql field definitions

---

ext_tables.sql

We're adding core code to add default sql definitions derived from TCA. Fields of type=email do not need to be set anymore.
Releases: main
Related: https://forge.typo3.org/issues/101653

[TASK] Remove all type=check sql field definitions

---

Configuration/TCA/tx_styleguide_elements_basic.php
Configuration/TCA/tx_styleguide_l10nreadonly.php

The render type `checkboxToggle` has no labels for checked or unchecked states. These are only available for `checkboxLabeledToggle`.
See also TYPO3-Documentation/TYPO3CMS-Reference-TCA#767

[BUGFIX] Remove wrong labels for render type `checkboxToggle`

---

Configuration/TCA/tx_styleguide_elements_basic.php

The TCA type is currently only used as sys_language_uid system field, but can also be used in user land as a business field. To provide a set of possibilities for the type, a simple implementation is added.

[TASK] Add example for TCA type='language'

---

ext_tables.sql

We're adding core code to add default sql definitions derived from TCA. Fields of type=group do not need to be set anymore.
See: https://review.typo3.org/c/Packages/TYPO3.CMS/+/81016
Releases: main
Related: https://forge.typo3.org/issues/101914

[TASK] Remove all type=imageManipulation sql field definitions

---

ext_tables.sql

We're adding core code to add default sql definitions derived from TCA. Fields of type=group do not need to be set anymore.
See: https://review.typo3.org/c/Packages/TYPO3.CMS/+/80990
Releases: main
Related: https://forge.typo3.org/issues/101908

[TASK] Remove all type=group sql field definitions

---

ext_tables.sql

We're adding core code to add default sql definitions derived from TCA. Fields of type=text do not need to be set anymore.
See: https://review.typo3.org/c/Packages/TYPO3.CMS/+/81127
Releases: main
Related: https://forge.typo3.org/issues/101986

[TASK] Remove all type=text sql field definitions

---

Configuration/TCA/tx_styleguide_elements_basic.php
ext_tables.sql

The required table covers this already and
elements_basic table should not have
required fields.

[TASK] TCA: Avoid 'required' example in elements_basic

---

ext_tables.sql

We're adding core code to add default sql definitions derived from TCA. Fields of type=color do not need to be set anymore.
See: https://review.typo3.org/c/Packages/TYPO3.CMS/+/81366
Releases: main
Related: https://forge.typo3.org/issues/102107

[TASK] Remove all type=color sql field definitions

---

ext_tables.sql

We're adding core code to add default sql definitions derived from TCA. Fields of type=radio do not need to be set anymore.
See: https://review.typo3.org/c/Packages/TYPO3.CMS/+/81426
Releases: main
Related: https://forge.typo3.org/issues/102163

[TASK] Remove all type=radio sql field definitions

---

ext_tables.sql

We're adding core code to add default sql definitions derived from TCA. Fields of type=inline do not need to be set anymore.
See: https://review.typo3.org/c/Packages/TYPO3.CMS/+/81488
Releases: main
Related: https://forge.typo3.org/issues/102210

[TASK] Remove all type=inline sql field definitions and child relations

---

Classes/TcaDataGenerator/FieldGenerator/TypeInline1n.php
Configuration/TCA/tx_styleguide_inline_1nreusabletable.php
Configuration/TCA/tx_styleguide_inline_1nreusabletable_child.php
ext_tables.sql

An example for foreign_match_fields is added, which demonstrates how to reuse a child table in multiple type inline fields.
Releases: main

[FEATURE] TCA inline foreign_match_fields example

---

ext_tables.sql

We're adding core code to add default sql definitions derived from TCA. Fields of type=number do not need to be set anymore.
See: https://review.typo3.org/c/Packages/TYPO3.CMS/+/81532
Releases: main
Related: https://forge.typo3.org/issues/102237

[TASK] Remove all type=number sql field definitions

---

README.md
Resources/Private/Templates/Backend/Index.html

Shorten README.md to relevant text valid when
styleguide is merged into core monorepo. Also
remove the 'legal' note of the tree icon since
it was meanwhile changed by us to a different one.

[TASK] Streamline README.md

---

Configuration/Backend/Modules.php
README.md
Resources/Private/Language/locallang.xlf
Tests/Acceptance/Backend/ModuleCest.php

Update backend labels shown in "About TYPO3 CMS" module. Move backend module to group "System".

[TASK] Update backend module configuration

---

Build/UnitTestsBootstrap.php

The third argument on SystemEnvironmentBuilder::run() is obsolete.

[TASK] Update styleguide UnitTestsBootstrap.php

---

Configuration/TypoScript/setup.typoscript

Some left over usages pointing to
typo3conf/ext/styleguide directly.
This is a backport for v12 compose-mode compatibility where files need to be referenced via API for path resolution to work (to use /_assets/… instead of a static path pointing to /typo3conf/).
Resolves: #102235
Releases: main, 12, 11
Upstream: https://review.typo3.org/c/Packages/TYPO3.CMS/+/81649

[TASK] Clean up usages of typo3conf/ext/styleguide
